# docker-compose.yml
version: "3"
services:
  app:
    build: ../
    depends_on:
    - postgres
    ports:
    - "3001:3001"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: public
      POSTGRES_USER: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql